baseURL = 'https://shotbymishkat.com/'
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/New_York"
timeout = "120s"
title = "Shot By Mishkat"
theme = "gallery"

[params]
  defaultTheme = "dark"
  description = "Photography Portfolio"
  title = "Shot By Mishkat"
  enableDownload = false
  [params.author]
    email = "shotbymishkat@gmail.com"
    name = "Shot By Mishkat"
  [params.socialIcons]
    instagram = "https://www.instagram.com/shotbymishkat/"
    #facebook = "https://www.facebook.com/"
    #github = "https://github.com/"
    #youtube = "https://www.youtube.com/"
    email = "mailto:shotbymishkat@gmail.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[menu]
  [[menu.footer]]
    name = "Â© 2026 Shot By Mishkat"
    url = "/license/"
    weight = 1

[services]
  [services.rss]
    limit = 100
